### ISSUE TITLE
Deployment on Amazon EC2/S3

### ISSUE THREAD

**Issue by hasanr68** [drachtio/drachtio-siprec-recording-server#38]
Hello all,

Unsure where to ask. Want to deploy this with Opensips on an Amazon EC2 server, however, can't seem to find any instructions. Was thinking of saving the audio files on an S3 bucket and drachtio to pull from S3 - does that work? Also - is there a Web UI that we can use to retrieve the files?

Thanks.

**Comment by davehorton** [comment]
It sounds like you want opensips to save recordings to S3, and drachtio to pull them from there?  This application will not help you, and in fact I am not familiar enough with opensips to know whether it can do that.

What you _can_ do with opensips is this:
- opensips is the siprec client
- this application (running with drachtio) is the siprec server
- this application could be modified to make recordings and upload them to S3
- all of the above can be run on EC2 instances

**Comment by hasanr68** [comment]
Hi again.

Thanks for taking the time to respond. To clarify, as things stand, the following is what I can do as things stand:

1. Have one instance of EC2 running Opensips, and another instance to run Drachtio+this app (siprec server).
2. Save the recordings on EC2 instance (presumably the one running this app).

How do I access the recordings? Is there a UI pls?
Apologies if I have misunderstood something.

Thanks

**Comment by davehorton** [comment]
Yes, that is correct.  I imagine you could run both servers on one EC2 instance as well, though for a scalable solution you might not want to.

There are two options in this project
- you can use rtpengine, in which case the recordings are made to pcap files in a directory of your choosing.
- you can use freeswitch, in which case the recordings are made to wav files in a directory of your choosing.

Of course, it is a node.js app so you could also modify the app to upload recordings to S3 if you wanted

**Comment by hasanr68** [comment]
Hi again Dave,

Thanks a lot for taking the time to explain. Forgot to mention, we are using rtpproxy, I believe we can save in a directory of our choice. Does the app have some kind of web-based UI that we can use to access the recordings?

**Comment by davehorton** [comment]
ok, sorry this application is designed to work with rtpengine or freeswitch.  You are welcome to try to modify to work with rtpproxy, but at that point you are on your own.

**Comment by hasanr68** [comment]
Thanks a lot once again.
