### ISSUE TITLE
Question: it is possible that calls will be recorded

### ISSUE THREAD

**Issue by malvarado611** [drachtio/drachtio-siprec-recording-server#42]
I am recording calls using drachtio server, drachtio recording and rtpengine, and everything work fine, but I would like to define which calls are recorded and which are not. It is possible to define this in drachtio server. I hope you can answer me.

Greetings,
Miguel Alvarado

**Comment by davehorton** [comment]
yes if. you are using rtpengine to record the calls, you can specify in the offer command whether or not you want the call to be recorded.  Is that what you mean?  Would you know at the beginning of the call whether or not you want to record it?

**Comment by malvarado611** [comment]
Yes, I would like to validate first if the call that reaches our server is a call that I want to record. So this would be possible using rtpengie. This could be done by configuration file or command line.

Saludos,
Miguel Alvarado
________________________________
De: Dave Horton ***@***.***>
Enviado: martes, 18 de mayo de 2021 19:01
Para: drachtio/drachtio-siprec-recording-server ***@***.***>
Cc: Miguel Alvarado ***@***.***>; Author ***@***.***>
Asunto: Re: [drachtio/drachtio-siprec-recording-server] Question: it is possible that calls will be recorded (#42)


yes if. you are using rtpengine to record the calls, you can specify in the offer command whether or not you want the call to be recorded. Is that what you mean? Would you know at the beginning of the call whether or not you want to record it?

**Comment by davehorton** [comment]
So, basically, instead of always setting this flag:

https://github.com/drachtio/drachtio-siprec-recording-server/blob/5d2573d8d77467caf0ce4a1e55207b48dc859120/lib/rtpengine-call-handler.js#L42

you want to change the code to only set that if you've decided to record the call

**Comment by malvarado611** [comment]
I can to change code for that, for example, only recording calls that origen number is 2000. The parameter that you mention is for this.

Thanks for your support.

Regardins,
Miguel Alvarado

El 18 may. 2021 7:25 p. m., Dave Horton ***@***.***> escribió:

So, basically, instead of always setting this flag:

https://github.com/drachtio/drachtio-siprec-recording-server/blob/5d2573d8d77467caf0ce4a1e55207b48dc859120/lib/rtpengine-call-handler.js#L42

you want to change the code to only set that if you've decided to record the call

**Comment by malvarado611** [comment]
I can change the code for that, for example, only recording calls that origen number is 2000. The parameter that you mention is for this.

Thanks for your support.

Regardins,
Miguel Alvarado
________________________________
De: Dave Horton ***@***.***>
Enviado: miércoles, 19 de mayo de 2021 06:30
Para: drachtio/drachtio-siprec-recording-server ***@***.***>
Cc: Miguel Alvarado ***@***.***>; Author ***@***.***>
Asunto: Re: [drachtio/drachtio-siprec-recording-server] Question: it is possible that calls will be recorded (#42)


Closed #42<https://github.com/drachtio/drachtio-siprec-recording-server/issues/42>.
