### ISSUE TITLE
get access to audio stream

### ISSUE THREAD

**Issue by vovanb** [drachtio/drachtio-siprec-recording-server#45]
Hello,
I have request to implement siprec server which will stream Audio to external endpoint (MS, Google) for STT (Speech to text) .
Can you please point me where in server code I can get access to media stream ?
Thanks

**Comment by davehorton** [comment]
you would need to connect the call through freeswitch, like this app does, but then you would need to use a freeswitch plugin (like my [mod_audio_fork](https://github.com/drachtio/drachtio-freeswitch-modules/tree/master/modules/mod_audio_fork) to get access the audio stream.

Not that difficult, but not a feature that is current implemented in this repo
