### ISSUE TITLE
Avaya SBCE + FreeSwitch Empty recordings

### ISSUE THREAD

**Issue by amolinero** [drachtio/drachtio-siprec-recording-server#61]
hi guys,
I have a deployment with Avaya SBCE (172.31.13.176), drachtio + redis (192.168.2.112) and freeswitch (192.168.2.111). It seems SIP signaling between all is going ok (second call leg, etc) but for every call 2 wav files are generated (caller and calle?) and, even files has size not zero, only silence is recorded. i have checked via tcpdump RTP is arriving to freeswitch host. Attached all the logs. any idea?

thanks in advance!     
[drach.log](https://github.com/drachtio/drachtio-siprec-recording-server/files/11343375/drach.log)
[FS.log](https://github.com/drachtio/drachtio-siprec-recording-server/files/11343376/FS.log)
[app.log](https://github.com/drachtio/drachtio-siprec-recording-server/files/11343377/app.log)

**Comment by amolinero** [comment]
solved...

**Comment by davehorton** [comment]
what was the issue?

**Comment by amolinero** [comment]
I am using your docker image davehorton/freeswitch-hairpin:latest to test so i had to resolve the way to expose rtpports and ip to Avaya SBCE limiting this range (defining --rtp-range-start, --rtp-range-end YYYYY and --ext-rtp-ip) as map a large range of ports causes memory problems in docker. 
Now i am going to test https://github.com/drachtio/drachtio-freeswitch-modules/blob/main/modules/mod_audio_fork/README.md to get audio stream so i can work with it (for biometric purposes). just quick question, is in your davehorton/freeswitch-hairpin image already installed and ready to work this module? any advice? thanks
