### ISSUE TITLE
RtpEngineError: malformed/unexpected error for type DTMF

### ISSUE THREAD

**Issue by vdharashive** [drachtio/drachtio-siprec-recording-server#68]
67|drachtio-siprec-recording-server  | {"level":30,"time":1689152309658,"msg":"call connected successfully, using rtpengine at {\"host\":\"localhost\",\"port\":22222}","pid":1176370,"hostname":"ip-172-31-29-233","callid":"169958058312720238578@50.19.121.248","v":1}
67|drachtio-siprec-recording-server  | RtpEngineError: malformed/unexpected message format {"callid":"169958058312720238578@50.19.121.248","source_tag":"5810fd55-e64d-46b2-bfcc-15e5ca553e8a","tags":["5810fd55-e64d-46b2-bfcc-15e5ca553e8a","1c601966398"],"type":"DTMF","timestamp":1689152321,"source_ip":"50.19.121.248","event":6,"duration":57,"volume":10}
67|drachtio-siprec-recording-server  |     at Client._onMessage (/home/admin/apps/drachtio-siprec-recording-server/node_modules/rtpengine-client/lib/client.js:85:26)
67|drachtio-siprec-recording-server  |     at Socket.emit (node:events:513:28)
67|drachtio-siprec-recording-server  |     at UDP.onMessage [as onmessage] (node:dgram:933:8)
PM2                               | App [drachtio-siprec-recording-server:67] exited with code [1] via signal [SIGINT]
PM2                               | App [drachtio-siprec-recording-server:67] starting in -fork mode-
PM2                               | App [drachtio-siprec-recording-server:67] online
67|drachtio-siprec-recording-server  | {"level":30,"time":1689152321731,"msg":"attempting inbound connection","pid":1176506,"hostname":"ip-172-31

**Comment by davehorton** [comment]
steps to recreate please?

**Comment by vdharashive** [comment]
i am sending call as siprec from audiocodes for recording there is dtmf input given by customer on call at that time the application receive error

**Comment by vdharashive** [comment]
@xquanluu thanks for fixing this
